---
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    layout:
      author:
        hidden: true

  - title: Needs My Review
    filters: is:open review-requested:@me -author:app/dependabot
    layout:
      repo:
        width: 6

  - title: Commented
    filters: commenter:@me

  - title: pragmaticivan [bots]
    filters: is:pr is:open user:pragmaticivan author:app/dependabot

  - title: nestjs-otel
    filters: "is:open repo:pragmaticivan/nestjs-otel"

  - title: opentelemetry-lambda
    filters: "is:open repo:open-telemetry/opentelemetry-lambda"

issuesSections:
  - title: Creator
    filters: author:@me

  - title: Commented
    filters: is:open commenter:@me

  - title: opentelemetry-lambda
    filters: is:open repo:open-telemetry/opentelemetry-lambda

  - title: Assigned
    filters: is:open assignee:@me

pager:
  diff: diffnav

defaults:
  view: repo
  refetchIntervalMinutes: 10
  layout:
    prs:
      repoName:
        grow: true,
        width: 10
        hidden: false
      base:
        hidden: true
  preview:
    open: true
    width: 70
  prsLimit: 20
  issuesLimit: 20

repoPaths:
  :owner/:repo: ~/Code/:owner/:repo

keybindings:
  universal:
    - key: g
      command: >
        cd {{.RepoPath}} && lazygit
  prs:
    - name: add
      key: A
      command: >
        cd {{.RepoPath}} && git add -A && lazygit

    - name: open in vscode
      key: V
      command: >
        cd {{.RepoPath}} && gh pr checkout {{.PrNumber}} && code .

    - name: approve
      key: v
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approve Comment: ')" {{.PrNumber}}

    - name: merge
      key: m
      command: >
        gh pr merge --repo {{.RepoName}} {{.PrNumber}} --delete-branch

theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
  colors:
    text:
      primary: "#cad3f5"
      secondary: "#b7bdf8"
      inverted: "#181926"
      faint: "#b8c0e0"
      warning: "#eed49f"
      success: "#a6da95"
      error: "#ed8796"
    background:
      selected: "#363a4f"
    border:
      primary: "#b7bdf8"
      secondary: "#494d64"
      faint: "#363a4f"
